# -*- coding: utf-8 -*-
"""recipe_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_CLQKc-JBHUPnoWZjp3o43biMmjpD3Lo
"""

import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter
df = pd.read_csv("/content/recipe.csv")
print(df.head())
print("\nColumns in the dataset:")
print(df.columns.tolist())
print("\nBasic Info:")
print(df.info())
top_recipes = df[df['Rating'] >= 4.5]
print("\nNumber of top-rated recipes:", len(top_recipes))
all_ingredients = []
for ing_list in top_recipes['Ingredients']:
    ingredients = eval(ing_list) if isinstance(ing_list, str) else ing_list
    all_ingredients.extend(ingredients)
ingredient_counts = Counter(all_ingredients)
top_10_ingredients = ingredient_counts.most_common(10)
print("\nTop 10 Ingredients in Top-Rated Recipes:")
print(top_10_ingredients)
#  Visualize Ingredient Frequency
ingredients, counts = zip(*top_10_ingredients)
plt.figure(figsize=(8, 5))
plt.barh(ingredients, counts, color='skyblue')
plt.xlabel("Count")
plt.ylabel("Ingredient")
plt.title("Top 10 Ingredients in Top-Rated Recipes")
plt.gca().invert_yaxis()  # Show highest on top
plt.show()
# Healthy Recipe Analysis
healthy_recipes = df[(df['Calories'] < 300) & (df['FatContent'] < 10)] # Define "healthy" recipes: Calories < 300 and FatContent < 10
print("\nNumber of healthy recipes:", len(healthy_recipes))
# Average calories of healthy recipes
avg_calories = healthy_recipes['Calories'].mean()
print("Average calories of healthy recipes:", round(avg_calories, 2))
# Calories vs Protein Visualization
plt.figure(figsize=(6, 4))
plt.scatter(df['Calories'], df['ProteinContent'], alpha=0.6, color='green')
plt.xlabel("Calories")
plt.ylabel("Protein (g)")
plt.title("Calories vs Protein Content")
plt.show()
#  Top 5 Healthiest Recipes
df['HealthScore'] = df['ProteinContent'] - (df['FatContent'] + df['Calories'] / 50) # Define health score
# Sort recipes by HealthScore
top_5_healthiest = df.sort_values(by='HealthScore', ascending=False).head(5)
print("\nTop 5 Healthiest Recipes:")
print(top_5_healthiest[['Name', 'Calories', 'ProteinContent', 'FatContent', 'Rating', 'HealthScore']])